// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROOT_DIVERPC_H_
#define FLATBUFFERS_GENERATED_ROOT_DIVERPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace DiveRpc {

struct Packet;
struct PacketBuilder;

struct VersionCode;

struct Ignored;
struct IgnoredBuilder;

struct Path;
struct PathBuilder;

struct FileInfo;
struct FileInfoBuilder;

enum Payload : uint8_t {
  Payload_NONE = 0,
  Payload_HandshakeRequest = 1,
  Payload_HandshakeResponse = 2,
  Payload_PingMessage = 3,
  Payload_PongMessage = 4,
  Payload_Pm4CaptureRequest = 5,
  Payload_Pm4CaptureResponse = 6,
  Payload_DownloadFileRequest = 7,
  Payload_DownloadFileResponse = 8,
  Payload_FileSizeRequest = 9,
  Payload_FileSizeResponse = 10,
  Payload_RemoveFileRequest = 11,
  Payload_RemoveFileResponse = 12,
  Payload_MIN = Payload_NONE,
  Payload_MAX = Payload_RemoveFileResponse
};

inline const Payload (&EnumValuesPayload())[13] {
  static const Payload values[] = {
    Payload_NONE,
    Payload_HandshakeRequest,
    Payload_HandshakeResponse,
    Payload_PingMessage,
    Payload_PongMessage,
    Payload_Pm4CaptureRequest,
    Payload_Pm4CaptureResponse,
    Payload_DownloadFileRequest,
    Payload_DownloadFileResponse,
    Payload_FileSizeRequest,
    Payload_FileSizeResponse,
    Payload_RemoveFileRequest,
    Payload_RemoveFileResponse
  };
  return values;
}

inline const char * const *EnumNamesPayload() {
  static const char * const names[14] = {
    "NONE",
    "HandshakeRequest",
    "HandshakeResponse",
    "PingMessage",
    "PongMessage",
    "Pm4CaptureRequest",
    "Pm4CaptureResponse",
    "DownloadFileRequest",
    "DownloadFileResponse",
    "FileSizeRequest",
    "FileSizeResponse",
    "RemoveFileRequest",
    "RemoveFileResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayload(Payload e) {
  if (::flatbuffers::IsOutRange(e, Payload_NONE, Payload_RemoveFileResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayload()[index];
}

template <bool B = false>
bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type);
template <bool B = false>
bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum StatusCode : int32_t {
  StatusCode_Success = 0,
  StatusCode_Unknown = 1,
  StatusCode_NotFound = 2,
  StatusCode_MIN = StatusCode_Success,
  StatusCode_MAX = StatusCode_NotFound
};

inline const StatusCode (&EnumValuesStatusCode())[3] {
  static const StatusCode values[] = {
    StatusCode_Success,
    StatusCode_Unknown,
    StatusCode_NotFound
  };
  return values;
}

inline const char * const *EnumNamesStatusCode() {
  static const char * const names[4] = {
    "Success",
    "Unknown",
    "NotFound",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatusCode(StatusCode e) {
  if (::flatbuffers::IsOutRange(e, StatusCode_Success, StatusCode_NotFound)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatusCode()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) VersionCode FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t major_;
  uint32_t minor_;

 public:
  VersionCode()
      : major_(0),
        minor_(0) {
  }
  VersionCode(uint32_t _major, uint32_t _minor)
      : major_(::flatbuffers::EndianScalar(_major)),
        minor_(::flatbuffers::EndianScalar(_minor)) {
  }
  uint32_t major() const {
    return ::flatbuffers::EndianScalar(major_);
  }
  uint32_t minor() const {
    return ::flatbuffers::EndianScalar(minor_);
  }
};
FLATBUFFERS_STRUCT_END(VersionCode, 8);

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8,
    VT_MESSAGE = 10
  };
  DiveRpc::StatusCode status() const {
    return static_cast<DiveRpc::StatusCode>(GetField<int32_t>(VT_STATUS, 0));
  }
  DiveRpc::Payload payload_type() const {
    return static_cast<DiveRpc::Payload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  const DiveRpc::VersionCode *payload_as_HandshakeRequest() const {
    return payload_type() == DiveRpc::Payload_HandshakeRequest ? static_cast<const DiveRpc::VersionCode *>(payload()) : nullptr;
  }
  const DiveRpc::VersionCode *payload_as_HandshakeResponse() const {
    return payload_type() == DiveRpc::Payload_HandshakeResponse ? static_cast<const DiveRpc::VersionCode *>(payload()) : nullptr;
  }
  const DiveRpc::Ignored *payload_as_PingMessage() const {
    return payload_type() == DiveRpc::Payload_PingMessage ? static_cast<const DiveRpc::Ignored *>(payload()) : nullptr;
  }
  const DiveRpc::Ignored *payload_as_PongMessage() const {
    return payload_type() == DiveRpc::Payload_PongMessage ? static_cast<const DiveRpc::Ignored *>(payload()) : nullptr;
  }
  const DiveRpc::Ignored *payload_as_Pm4CaptureRequest() const {
    return payload_type() == DiveRpc::Payload_Pm4CaptureRequest ? static_cast<const DiveRpc::Ignored *>(payload()) : nullptr;
  }
  const DiveRpc::Path *payload_as_Pm4CaptureResponse() const {
    return payload_type() == DiveRpc::Payload_Pm4CaptureResponse ? static_cast<const DiveRpc::Path *>(payload()) : nullptr;
  }
  const DiveRpc::Path *payload_as_DownloadFileRequest() const {
    return payload_type() == DiveRpc::Payload_DownloadFileRequest ? static_cast<const DiveRpc::Path *>(payload()) : nullptr;
  }
  const DiveRpc::FileInfo *payload_as_DownloadFileResponse() const {
    return payload_type() == DiveRpc::Payload_DownloadFileResponse ? static_cast<const DiveRpc::FileInfo *>(payload()) : nullptr;
  }
  const DiveRpc::Path *payload_as_FileSizeRequest() const {
    return payload_type() == DiveRpc::Payload_FileSizeRequest ? static_cast<const DiveRpc::Path *>(payload()) : nullptr;
  }
  const DiveRpc::FileInfo *payload_as_FileSizeResponse() const {
    return payload_type() == DiveRpc::Payload_FileSizeResponse ? static_cast<const DiveRpc::FileInfo *>(payload()) : nullptr;
  }
  const DiveRpc::Path *payload_as_RemoveFileRequest() const {
    return payload_type() == DiveRpc::Payload_RemoveFileRequest ? static_cast<const DiveRpc::Path *>(payload()) : nullptr;
  }
  const DiveRpc::Ignored *payload_as_RemoveFileResponse() const {
    return payload_type() == DiveRpc::Payload_RemoveFileResponse ? static_cast<const DiveRpc::Ignored *>(payload()) : nullptr;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_STATUS, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyPayload(verifier, payload(), payload_type()) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(DiveRpc::StatusCode status) {
    fbb_.AddElement<int32_t>(Packet::VT_STATUS, static_cast<int32_t>(status), 0);
  }
  void add_payload_type(DiveRpc::Payload payload_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(Packet::VT_PAYLOAD, payload);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(Packet::VT_MESSAGE, message);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    DiveRpc::StatusCode status = DiveRpc::StatusCode_Success,
    DiveRpc::Payload payload_type = DiveRpc::Payload_NONE,
    ::flatbuffers::Offset<void> payload = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_payload(payload);
  builder_.add_status(status);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Packet> CreatePacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    DiveRpc::StatusCode status = DiveRpc::StatusCode_Success,
    DiveRpc::Payload payload_type = DiveRpc::Payload_NONE,
    ::flatbuffers::Offset<void> payload = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return DiveRpc::CreatePacket(
      _fbb,
      status,
      payload_type,
      payload,
      message__);
}

struct Ignored FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IgnoredBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct IgnoredBuilder {
  typedef Ignored Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit IgnoredBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Ignored> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Ignored>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Ignored> CreateIgnored(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  IgnoredBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Path FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PathBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct PathBuilder {
  typedef Path Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(Path::VT_PATH, path);
  }
  explicit PathBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Path> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Path>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Path> CreatePath(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0) {
  PathBuilder builder_(_fbb);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Path> CreatePathDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return DiveRpc::CreatePath(
      _fbb,
      path__);
}

struct FileInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FileInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4,
    VT_SIZE = 6
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyField<uint64_t>(verifier, VT_SIZE, 8) &&
           verifier.EndTable();
  }
};

struct FileInfoBuilder {
  typedef FileInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(FileInfo::VT_PATH, path);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(FileInfo::VT_SIZE, size, 0);
  }
  explicit FileInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FileInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FileInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FileInfo> CreateFileInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    uint64_t size = 0) {
  FileInfoBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FileInfo> CreateFileInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    uint64_t size = 0) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return DiveRpc::CreateFileInfo(
      _fbb,
      path__,
      size);
}

template <bool B>
inline bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type) {
  switch (type) {
    case Payload_NONE: {
      return true;
    }
    case Payload_HandshakeRequest: {
      return verifier.template VerifyField<DiveRpc::VersionCode>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case Payload_HandshakeResponse: {
      return verifier.template VerifyField<DiveRpc::VersionCode>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case Payload_PingMessage: {
      auto ptr = reinterpret_cast<const DiveRpc::Ignored *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_PongMessage: {
      auto ptr = reinterpret_cast<const DiveRpc::Ignored *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Pm4CaptureRequest: {
      auto ptr = reinterpret_cast<const DiveRpc::Ignored *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Pm4CaptureResponse: {
      auto ptr = reinterpret_cast<const DiveRpc::Path *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_DownloadFileRequest: {
      auto ptr = reinterpret_cast<const DiveRpc::Path *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_DownloadFileResponse: {
      auto ptr = reinterpret_cast<const DiveRpc::FileInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_FileSizeRequest: {
      auto ptr = reinterpret_cast<const DiveRpc::Path *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_FileSizeResponse: {
      auto ptr = reinterpret_cast<const DiveRpc::FileInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_RemoveFileRequest: {
      auto ptr = reinterpret_cast<const DiveRpc::Path *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_RemoveFileResponse: {
      auto ptr = reinterpret_cast<const DiveRpc::Ignored *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPayload(
        verifier,  values->Get(i), types->GetEnum<Payload>(i))) {
      return false;
    }
  }
  return true;
}

inline const DiveRpc::Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<DiveRpc::Packet>(buf);
}

inline const DiveRpc::Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<DiveRpc::Packet>(buf);
}

template <bool B = false>
inline bool VerifyPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<DiveRpc::Packet>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<DiveRpc::Packet>(nullptr);
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DiveRpc::Packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DiveRpc::Packet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DiveRpc

#endif  // FLATBUFFERS_GENERATED_ROOT_DIVERPC_H_
