/*
 * Copyright (c) 2017 Rob Clark <robdclark@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sub license,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial portions
 * of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <GLES3/gl32.h>
#include "test-util-3d.h"

static EGLint const config_attribute_list[] = {
	EGL_RED_SIZE, 8,
	EGL_GREEN_SIZE, 8,
	EGL_BLUE_SIZE, 8,
	EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
	EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
	EGL_DEPTH_SIZE, 8,
	EGL_NONE
};

static const EGLint context_attribute_list[] = {
	EGL_CONTEXT_CLIENT_VERSION, 2,
	EGL_NONE
};

static EGLDisplay display;
static EGLConfig config;
static EGLint num_config;
static EGLContext context;

static const struct {
	const char *str;
	GLenum glenum;
#define ENUM(x) { #x, x }
} enums[] = {
	ENUM(GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS),
	ENUM(GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE),
	ENUM(GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS),
	ENUM(GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS),
	ENUM(GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS),
	ENUM(GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS),
	ENUM(GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS),
	ENUM(GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS),
	ENUM(GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS),

	ENUM(GL_MAX_COMBINED_ATOMIC_COUNTERS),
	ENUM(GL_MAX_COMPUTE_ATOMIC_COUNTERS),
	ENUM(GL_MAX_FRAGMENT_ATOMIC_COUNTERS),
	ENUM(GL_MAX_VERTEX_ATOMIC_COUNTERS),
	ENUM(GL_MAX_GEOMETRY_ATOMIC_COUNTERS),
	ENUM(GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS),
	ENUM(GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS),

	ENUM(GL_MAX_COMBINED_IMAGE_UNIFORMS),
	ENUM(GL_MAX_COMPUTE_IMAGE_UNIFORMS),
	ENUM(GL_MAX_FRAGMENT_IMAGE_UNIFORMS),
	ENUM(GL_MAX_VERTEX_IMAGE_UNIFORMS),
	ENUM(GL_MAX_GEOMETRY_IMAGE_UNIFORMS),
	ENUM(GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS),
	ENUM(GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS),

	ENUM(GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS),
	ENUM(GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS),
	ENUM(GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS),
	ENUM(GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS),
	ENUM(GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS),
	ENUM(GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS),
	ENUM(GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS),

	ENUM(GL_MAX_IMAGE_UNITS),
	ENUM(GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS),
	ENUM(GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS),
	ENUM(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS),
	ENUM(GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS),
	ENUM(GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS),
	ENUM(GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS),

	ENUM(GL_MAX_UNIFORM_BLOCK_SIZE),
	ENUM(GL_MAX_UNIFORM_BUFFER_BINDINGS),
	ENUM(GL_MAX_UNIFORM_LOCATIONS),
	ENUM(GL_MAX_COMBINED_UNIFORM_BLOCKS),
	ENUM(GL_MAX_COMPUTE_UNIFORM_BLOCKS),
	ENUM(GL_MAX_FRAGMENT_UNIFORM_BLOCKS),
	ENUM(GL_MAX_VERTEX_UNIFORM_BLOCKS),
	ENUM(GL_MAX_GEOMETRY_UNIFORM_BLOCKS),
	ENUM(GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS),
	ENUM(GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS),

	ENUM(GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS),

	ENUM(GL_MAX_COMPUTE_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_FRAGMENT_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_VERTEX_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_GEOMETRY_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS),
	ENUM(GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS),

	ENUM(GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES),

	ENUM(GL_MAX_COMPUTE_SHARED_MEMORY_SIZE),
	ENUM(GL_MAX_COMPUTE_WORK_GROUP_COUNT),
	ENUM(GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS),
	ENUM(GL_MAX_COMPUTE_WORK_GROUP_SIZE),

	ENUM(GL_MAX_FRAGMENT_INPUT_COMPONENTS),
	ENUM(GL_MAX_FRAGMENT_UNIFORM_VECTORS),
	ENUM(GL_MAX_VERTEX_UNIFORM_VECTORS),

	ENUM(GL_MAX_GEOMETRY_INPUT_COMPONENTS),
	ENUM(GL_MAX_GEOMETRY_OUTPUT_COMPONENTS),
	ENUM(GL_MAX_GEOMETRY_OUTPUT_VERTICES),
	ENUM(GL_MAX_GEOMETRY_SHADER_INVOCATIONS),
	ENUM(GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS),

	ENUM(GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS),
	ENUM(GL_MAX_TESS_CONTROL_INPUT_COMPONENTS),
	ENUM(GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS),
	ENUM(GL_MAX_TESS_GEN_LEVEL),
	ENUM(GL_MAX_TESS_PATCH_COMPONENTS),

	ENUM(GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS),
	ENUM(GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS),

	ENUM(GL_MAX_VERTEX_ATTRIB_BINDINGS),
	ENUM(GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET),
	ENUM(GL_MAX_VERTEX_ATTRIBS),
	ENUM(GL_MAX_VERTEX_ATTRIB_STRIDE),
	ENUM(GL_MAX_VERTEX_OUTPUT_COMPONENTS),

	ENUM(GL_MAX_VARYING_COMPONENTS),
	ENUM(GL_MAX_VARYING_VECTORS),

	ENUM(GL_MAX_3D_TEXTURE_SIZE),
	ENUM(GL_MAX_ARRAY_TEXTURE_LAYERS),
	ENUM(GL_MAX_COLOR_ATTACHMENTS),
	ENUM(GL_MAX_COLOR_TEXTURE_SAMPLES),
	ENUM(GL_MAX_CUBE_MAP_TEXTURE_SIZE),
	ENUM(GL_MAX_DEPTH_TEXTURE_SAMPLES),
	ENUM(GL_MAX_DRAW_BUFFERS),
	ENUM(GL_MAX_ELEMENT_INDEX),
	ENUM(GL_MAX_ELEMENTS_INDICES),
	ENUM(GL_MAX_ELEMENTS_VERTICES),
	ENUM(GL_MAX_FRAMEBUFFER_HEIGHT),
	ENUM(GL_MAX_FRAMEBUFFER_SAMPLES),
	ENUM(GL_MAX_FRAMEBUFFER_WIDTH),
	ENUM(GL_MAX_INTEGER_SAMPLES),
	ENUM(GL_MAX_NUM_ACTIVE_VARIABLES),
	ENUM(GL_MAX_PROGRAM_TEXEL_OFFSET),
	ENUM(GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET),
	ENUM(GL_MAX_RENDERBUFFER_SIZE),
	ENUM(GL_MAX_SAMPLE_MASK_WORDS),
	ENUM(GL_MAX_SAMPLES),
	ENUM(GL_MAX_SHADER_STORAGE_BLOCK_SIZE),
	ENUM(GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS),
	ENUM(GL_MAX_TEXTURE_IMAGE_UNITS),
	ENUM(GL_MAX_TEXTURE_LOD_BIAS),
	ENUM(GL_MAX_TEXTURE_SIZE),
	ENUM(GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS),
	ENUM(GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS),
	ENUM(GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS),
	ENUM(GL_MAX_VIEWPORT_DIMS),
	ENUM(GL_TEXTURE_MAX_LEVEL),
	ENUM(GL_TEXTURE_MAX_LOD),
	ENUM(GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH),
};

static void test_limits()
{
	RD_START("limits", "");

	display = get_display();

	/* get an appropriate EGL frame buffer configuration */
	ECHK(eglChooseConfig(display, config_attribute_list, &config, 1, &num_config));
	DEBUG_MSG("num_config: %d", num_config);

	/* create an EGL rendering context */
	ECHK(context = eglCreateContext(display, config, EGL_NO_CONTEXT, context_attribute_list));
	ECHK(eglMakeCurrent(display, EGL_NO_SURFACE, EGL_NO_SURFACE, context));

	DEBUG_MSG("EGL Version %s", eglQueryString(display, EGL_VERSION));
	DEBUG_MSG("EGL Vendor %s", eglQueryString(display, EGL_VENDOR));
	DEBUG_MSG("EGL Extensions %s", eglQueryString(display, EGL_EXTENSIONS));
	DEBUG_MSG("GL Version %s", glGetString(GL_VERSION));
	DEBUG_MSG("GL extensions: %s", glGetString(GL_EXTENSIONS));

	/* print some compute limits (not strictly necessary) */
	GLint work_group_count[3] = {0};
	for (unsigned i = 0; i < 3; i++)
		glGetIntegeri_v (GL_MAX_COMPUTE_WORK_GROUP_COUNT, i, &work_group_count[i]);
	DEBUG_MSG("GL_MAX_COMPUTE_WORK_GROUP_COUNT: %d, %d, %d",
			work_group_count[0],
			work_group_count[1],
			work_group_count[2]);

	GLint work_group_size[3] = {0};
	for (unsigned i = 0; i < 3; i++)
		glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_SIZE, i, &work_group_size[i]);
	DEBUG_MSG("GL_MAX_COMPUTE_WORK_GROUP_SIZE: %d, %d, %d",
			work_group_size[0],
			work_group_size[1],
			work_group_size[2]);

	GLint val, i;
	for (i = 0; i < ARRAY_SIZE(enums); i++) {
		val = -1;
		glGetIntegerv(enums[i].glenum, &val);
		DEBUG_MSG("%40s: %d", enums[i].str, val);
	}

	RD_END();
}

int main(int argc, char *argv[])
{
	TEST_START();
	TEST(test_limits());
	TEST_END();

	return 0;
}

