name: Reusable Dive Build on Windows

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

jobs:
  build_host_windows:
    name: Build Host Windows ${{ inputs.build_type }}
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: jurplel/install-qt-action@d325aaf2a8baeeda41ad0b5d39f84a6af9bcf005 # v4.3.0
        with:
          version: 5.15.2
          arch: win64_msvc2019_64
      - uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2
      - name: Install Dive dependencies
        run: |
          python3 -m pip install mako
      # TODO: b/484082504 - Remove --build-with-cmake, need to ensure msbuild is on the Path on this runner first
      - name: Build Dive host tools with VS 2022
        run: |
          python3 -u scripts/build.py `
            --actions configure_host,build_host,install_host `
            --build-type $env:INPUTS_BUILD_TYPE `
            --build-with-cmake `
            --ci `
            --host-configure-additional-flags "`
              -DDIVE_BUILD_WITH_CRASHPAD=OFF"
        env:
          INPUTS_BUILD_TYPE: ${{ inputs.build_type }}
      - name: Run tests
        run: |
          ctest --output-on-failure -C $env:INPUTS_BUILD_TYPE --test-dir build/host
        env:
          INPUTS_BUILD_TYPE: ${{ inputs.build_type }}
